<a href="https://colab.research.google.com/github/nafi-rahman/ML-AI/blob/main/Exercises_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>




#Exercises
All of the exercises are focused on practicing the code above.
Pytorch Fundamentals 00


##1. Documentation reading

### 1.1 ```Torch.tensor```


Torch.tensor is used to define a tensor object in Pytorch.
A tensor object is a multidimentional matrix containing elements of a single datatype.
torch defines 10 tensor types including CPU & GPU
a pytorch tensor is 32-bit float(single) by default but it can also be, 16-bit float(half),64-bit float(double)

```
https://pytorch.org/docs/stable/tensors.html#torch.Tensor
```

### 1.2 ```Torch.cuda```

Torch.cuda is a package that adds support for cuda tensor types to utilize gpu computation.
it is lazily initiazed so it can use is_available() to determine the support.
```
https://pytorch.org/docs/stable/cuda.html
```

##2. Create random tensor with shape (7,7)

In [1]:
import torch

rand7_7 = torch.rand(7,7)
randInt7_7 = torch.randint(0,10,(7,7))

print(f"7x7 tensor made with torch.rand(): \n{rand7_7}\n") #uses a set range from 0-1
print(f"7x7 tensor made with torch.randInt(): \n{randInt7_7}\n") #the range can be set2

7x7 tensor made with torch.rand(): 
tensor([[0.7879, 0.4483, 0.6755, 0.0343, 0.1763, 0.2931, 0.7591],
        [0.5890, 0.6765, 0.7632, 0.5529, 0.2663, 0.2348, 0.3402],
        [0.6381, 0.0411, 0.8703, 0.8651, 0.4797, 0.4436, 0.2307],
        [0.8401, 0.2570, 0.3463, 0.1632, 0.8001, 0.3768, 0.4128],
        [0.7880, 0.8905, 0.1346, 0.9881, 0.3539, 0.1564, 0.1630],
        [0.8794, 0.5287, 0.7798, 0.0087, 0.1158, 0.8305, 0.5293],
        [0.7389, 0.4312, 0.1913, 0.5210, 0.7502, 0.9653, 0.1066]])

7x7 tensor made with torch.randInt(): 
tensor([[4, 2, 8, 2, 8, 6, 0],
        [6, 4, 0, 3, 9, 4, 9],
        [0, 5, 4, 1, 2, 8, 5],
        [5, 5, 0, 2, 9, 9, 2],
        [4, 5, 3, 0, 7, 9, 3],
        [2, 2, 6, 5, 9, 1, 2],
        [2, 3, 1, 2, 5, 7, 4]])



##3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [3]:
tensor_a = rand7_7
tensor_b = torch.rand(1,7)

tensor_c = torch.matmul(tensor_a,tensor_b.reshape(7,1))
tensor_c

tensor([[1.5114],
        [1.9139],
        [2.4643],
        [2.0328],
        [2.2201],
        [1.7987],
        [2.4084]])

##4. Set the random seed to 0 and do 2 & 3 over again.
```
The output should be:

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
#set random seed
torch.manual_seed(0)
#create tensors
tensor_a = torch.rand(7,7)
tensor_b = torch.rand(1,7)
#print shape
print(f"dim of tensor_a: {tensor_a.shape}\n dim of tensor_b: {tensor_b.shape}")
#reshape
tensor_b = tensor_b.reshape(7,1)
#matrix multiply
tensor_c = torch.matmul(tensor_a,tensor_b)
tensor_c

dim of tensor_a: torch.Size([7, 7])
 dim of tensor_b: torch.Size([1, 7])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

##5. random seed for gpu

In [9]:
import torch
torch.manual_seed(0)
tensor_cpu = torch.rand(2,2)
torch.manual_seed(0) #only works on the line below
tensor_gpu = torch.rand(2,2).to('cuda') #torch.cuda.seed() can also be used

print(f"cpu : \n{tensor_cpu}\n gpu: \n{tensor_gpu}\n")

cpu : 
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])
 gpu: 
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]], device='cuda:0')



##6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

output:
```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
torch.manual_seed(1234)
tensor_a = torch.rand(2,3).to('cuda')

tensor_b = torch.rand(2,3).to('cuda')

tensor_a, tensor_b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

##7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [20]:
#getting the shapes of tesnor
print(f"shape of 1: \n{tensor_a.shape}\n shape of 2: \n{tensor_b.shape}\n")
tensor_c = torch.matmul(tensor_a,tensor_b.reshape(3,2))
tensor_c

shape of 1: 
torch.Size([2, 3])
 shape of 2: 
torch.Size([2, 3])



tensor([[0.4759, 0.2931],
        [0.6074, 0.5855]], device='cuda:0')

##8. Find the maximum and minimum values of the output of 7.

In [22]:
print(f"max value: {tensor_c.max()}\n minimum value: {tensor_c.min()}")


max value: 0.6073753833770752
 minimum value: 0.2930890917778015


##9. Find the maximum and minimum index values of the output of 7.


In [23]:
print(f"max value index: {tensor_c.argmax()}\n minimum value index: {tensor_c.argmin()}")


max value index: 2
 minimum value index: 1


##10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

output:
```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])

```

In [24]:
torch.manual_seed(7)
tensor_a = torch.rand(1,1,1,10)
print(f"shape before: {tensor_a.shape}")
tensor_a = tensor_a.squeeze()
print(f"shape after: {tensor_a.shape}")

shape before: torch.Size([1, 1, 1, 10])
shape after: torch.Size([10])


#extra `https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html`

##QuickStart

###Working with data

In [34]:
#imports
import torch
import numpy as np
import matplotlib.pyplot as plt
import torchvision
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader
from torch import nn

In [30]:
#Loading and importing data from torchvision datasets
train_data = torchvision.datasets.FashionMNIST(
    root="data",
    train = True,
    download = True,
    transform = ToTensor(),

)

test_data = torchvision.datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform= ToTensor()
)



100%|██████████| 26421880/26421880 [00:02<00:00, 11820904.88it/s]


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 29515/29515 [00:00<00:00, 200380.19it/s]


Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 4422102/4422102 [00:01<00:00, 3745505.10it/s]


Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



100%|██████████| 5148/5148 [00:00<00:00, 25828082.53it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [33]:
#setting the batch size and passing dataset to dataloader
BATCH_SIZE = 64
#creating dataloaders
train_loader = DataLoader(train_data,batch_size=BATCH_SIZE)
test_loader = DataLoader(test_data,batch_size=BATCH_SIZE)

for x, y in test_loader:
  print(f"shape of x[n,c,h,w]: {x.shape}")
  print(f"shape of y: {y.shape} {y.dtype}")
  break

shape of x[n,c,h,w]: torch.Size([64, 1, 28, 28])
shape of y: torch.Size([64]) torch.int64


###creating a model
to define a neural network in pytorch,
* we will create a class to inherit from `nn.Module`.
* we will define the layers of the network in the `__init__ ` module
* we specify how the data will pass through the model in the forward function
* to accelerate the code we will use device agnostic code

In [39]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device being used: {device}")

class NN(nn.Module):
  def __init__(self):
    super().__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28,512),
        nn.ReLU(),
        nn.Linear(512,512),
        nn.ReLU(),
        nn.Linear(512,10)
    )

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits
model = NN().to(device)
print(model)

device being used: cuda
NN(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


###optimizing the model with optimizer and loss function

In [41]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)






###train / test loop

In [48]:
def train(dataloader,model ,loss_fn, optimizer):
  size = len(dataloader.dataset)
  model.train()
  for batch, (x,y) in enumerate(dataloader):
    x,y = x.to(device) , y.to(device)

    #compute error
    pred = model(x)
    loss = loss_fn(pred,y)

    #backpropagation
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    if batch % 100 == 0:
      loss, current = loss.item(), (batch + 1) * len(x)
      print(f"loss: {loss:>7f} [{current:>5d} {size:>5d}]")

def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")


###training the model

In [49]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_loader, model, loss_fn, optimizer)
    test(test_loader, model, loss_fn)
print("Done!")

Epoch 1
-------------------------------
loss: 2.171227 [   64 60000]
loss: 2.154419 [ 6464 60000]
loss: 2.097186 [12864 60000]
loss: 2.111963 [19264 60000]
loss: 2.072572 [25664 60000]
loss: 2.011855 [32064 60000]
loss: 2.037189 [38464 60000]
loss: 1.959713 [44864 60000]
loss: 1.963154 [51264 60000]
loss: 1.882406 [57664 60000]
Test Error: 
 Accuracy: 56.6%, Avg loss: 1.885315 

Epoch 2
-------------------------------
loss: 1.921265 [   64 60000]
loss: 1.881495 [ 6464 60000]
loss: 1.768294 [12864 60000]
loss: 1.808204 [19264 60000]
loss: 1.708477 [25664 60000]
loss: 1.665028 [32064 60000]
loss: 1.675680 [38464 60000]
loss: 1.582599 [44864 60000]
loss: 1.605408 [51264 60000]
loss: 1.490898 [57664 60000]
Test Error: 
 Accuracy: 60.3%, Avg loss: 1.517093 

Epoch 3
-------------------------------
loss: 1.585299 [   64 60000]
loss: 1.540761 [ 6464 60000]
loss: 1.400319 [12864 60000]
loss: 1.470542 [19264 60000]
loss: 1.359760 [25664 60000]
loss: 1.362487 [32064 60000]
loss: 1.363258 [38464 

###saving\loading the model

In [51]:
#save model
from pathlib import Path

#directory
MODEL_PATH = Path("models")
MODEL_PATH.mkdir(parents=True, exist_ok=True)
#path
MODEL_NAME = "01_model.pth"
MODEL_SAVE_PATH = MODEL_PATH/MODEL_NAME

#save state dict
print(f"saving model to : {MODEL_SAVE_PATH}")
torch.save(obj = model.state_dict(),
            f=MODEL_SAVE_PATH)

saving model to : models/01_model.pth


In [53]:
model = NN().to(device)
model.load_state_dict(torch.load(MODEL_SAVE_PATH))

<All keys matched successfully>

###inference

In [55]:
model.eval()
with torch.inference_mode():
  classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
    x = x.to(device)
    pred = model(x)
    predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f'Predicted: "{predicted}", Actual: "{actual}"')


Predicted: "Ankle boot", Actual: "Ankle boot"


#Tensors

Tensors are specialized DataStructers similar to arrays and matrices.
In PyTorch tensors are used to encode the inputs and outputs of a model, as well as it's parameters.

##Initializing a tensor

### Directly from data

In [56]:
data = [[1,2],
        [3,4]]

tensor_from_data = torch.tensor(data)

###from np array

In [57]:
data = [[1,2],
        [3,4]]

np_array = np.array(data)
tensor_from_array = torch.from_numpy(np_array)

###from another tensor

In [61]:
x_ones = torch.ones_like(tensor_from_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(tensor_from_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2991, 0.5749],
        [0.7849, 0.8664]]) 



###with random or constant value

In [62]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9151, 0.1209, 0.0112],
        [0.3414, 0.3411, 0.1549]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


##attributes of a tensor

In [63]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
